### ISSUE TITLE
Traffic diagram customization and node display enhancements.

### ISSUE THREAD

**Issue by swa1216** [knightss27/grafana-network-weathermap#10]
My English is not good, but I'm really happy to see this weathermap plugin appear.
But I have some function  hope you can help increase
1. the icon for traffic load can be moved？and define the name? and define the 0.x threshold
2. And upload my own background and icon not svg
3. Can the node just show the value not just in link
4. Can the link can turn?
![234](https://user-images.githubusercontent.com/108055710/175253292-4f617c1a-1cb9-43a2-ab35-ec9f0094fb16.JPG)

![123](https://user-images.githubusercontent.com/108055710/175253062-29665392-6ae3-4e99-b1ff-4974b29d51e9.JPG)
![789](https://user-images.githubusercontent.com/108055710/175254085-ac3fc2be-60ff-40f0-abbc-f4ffd8ec7e07.JPG)

**Comment by knightss27** [comment]
Hi! Thanks for using it!

To answer your questions:
1. I am happy to add the ability to move the threshold diagram. I also have another GitHub issue about decimal (0.x) percentages which I will also work to add. I am working on a small overhaul of link calculations as I am hoping to add the ability to choose different units.
2. See issue #9. Basically Grafana does not have a good way for me to let users upload images.
3. I will look into this.
4. I will also look into adding this. You could cheat something like this by using blank nodes (just set their label to nothing) and setting the links on both sides to the same data query source.

**Comment by knightss27** [comment]
Good news! Some of these updates should be releasing shortly with the v0.3.0 milestone.
1. I have allowed for some general customization of the traffic load diagram. This means moving its location, changing font size, and changing the scale's size. You can see the scale moved and altered in the diagram below.
2. I have implemented "turning" links. This will likely remain a fairly beta feature for a while, as it includes a lot of changes that may or may not work perfectly with more extensive testing. This is done with "connection" nodes, which is just a toggle on each node that allows you to turn it into a connection. More in depth documentation on how to use this feature will be published with the incoming release. You can also see this in the diagram below. Let me know what you think!

![image](https://user-images.githubusercontent.com/52898165/185336430-4cd62dca-4bc3-4092-9971-71f0e80a75c7.png)
