### ISSUE TITLE
LAG interface / Expression support

### ISSUE THREAD

**Issue by TFisd271** [knightss27/grafana-network-weathermap#12]
Thank you so much for this project, its awesome!

 A great additional feature would be a way to display traffic on aggregate interfaces.

When querying a LAG interface, snmp reports no traffic.  So to show LAG traffic in a Time Series panel, I need to query individual interfaces then use an expression like "queryA + queryB"  to get the aggregate traffic of the member interfaces.

Currently, Network Weathermap panel only allows for selecting a query to display traffic for a node.  If we were able to select an expression, then we could display LAG interface traffic in the map.  Which would be terrific!

[network weathermap lag](https://user-images.githubusercontent.com/108764215/177412578-b71d34cf-5da4-439b-a696-4a96a3e7f124.PNG)
.

**Comment by knightss27** [comment]
I'm looking into this. Annoyingly they are not very well documented by Grafana, so I am going to have to play around in my own environment to see what these look like. From what I can tell so far, the weathermap can see them, just they don't actually have any labels as names, so I'll probably have to look somewhere else to label them. This looks pretty doable thought.

**Comment by knightss27** [comment]
This should be fixed with auto-labeling of queries, to be released with v0.3.2. I've only had the chance to test with Prometheus queries however, so let me know in the future if this remains an issue.
