### ISSUE TITLE
Link tooltip almost unreadable

### ISSUE THREAD

**Issue by mzacchi** [knightss27/grafana-network-weathermap#15]
Hi @knightss27 ,

Thanks for the very useful plugin. I have set up a weathermap for my network and am facing an issue with the tooltips for the links. As you can see from the attached image, the text/background color combination is making it really hard to read the text. I couldn't find any way to change this setting, am I missing something?

![image](https://user-images.githubusercontent.com/55476929/179180285-33d76c7b-a868-48fa-a316-7bbc17b8be6d.png)

**Comment by knightss27** [comment]
No, that's a good catch. I hadn't added custom colors for the tooltip and it was meant to default to black background white text, but it looks like I only actually force the background color and the text color is inherited from elsewhere (which has presumably been changed here).

I'll try and add customization for that as soon as I can.

**Comment by knightss27** [comment]
Added for release with v0.3.0.
