### ISSUE TITLE
Host status 

### ISSUE THREAD

**Issue by bernierherve** [knightss27/grafana-network-weathermap#17]
Hi,

Many thanks for this plugin.
I used Network WeatherMap for long, and now migrating the dashboards to Grafana, i was very happy to find the Grafana version

Having the link status is very good, but having the host status directly on the map could be a good improvment.

I use LibreNMS as network monitoring tool, and the API let us know the status of the hosts : 1 = UP / 0 = DOWN.

If we can change the color of the nodes depending on their status, this plugins will be the best one for network admins :-)

**Comment by knightss27** [comment]
Would it be best if just the border of each node changes color? or do you think having the whole node change color would be even better?

**Comment by bernierherve** [comment]
Hello,
Thank you for this quick answer.
One or the other, or even font color can be possible, the one that is the simplest for you to code ;-)
The objective is to have a way to quickly see that a node is DOWN.
Thans in advance for your job

**Comment by knightss27** [comment]
Added for release with v0.3.2. Usage will be included in documentation updates.
![image](https://user-images.githubusercontent.com/52898165/189515179-93a2a327-879c-4bb7-8e3d-2765f40bd850.png)

**Comment by bernierherve** [comment]
Thank you very much for this enhancement.Waiting for release v0.3.2 to implement in my dashboards
Regards
H.
    Le dimanche 11 septembre 2022 à 08:23:54 UTC+2, Seth Knights ***@***.***> a écrit :  
 
 


Closed #17 as completed.

**Comment by bernierherve** [comment]
Many Thanks
    Le dimanche 23 octobre 2022 à 07:52:41 UTC+2, Seth Knights ***@***.***> a écrit :  
 
 


Sometime next week! University got in my way a bit, but I've managed to get some more time recently. I've just released the new version with host statuses on Github, but it will take a few days for Grafana to approve it.
