### ISSUE TITLE
Make threshold color pickers more visible

### ISSUE THREAD

**Issue by Slamkryp** [knightss27/grafana-network-weathermap#19]
Hi!

Great plugin! This is missing in zabbix which we use so i was thrilled to se this.

Running Grafana 9.1.3 and plugin 0.3.1

However, i seem to have a bit of a problem as i cant get the colors on links to work.
Not sure if this is grafana issue or plugin..

I cant set the colors. My list of thresholds looks like this.
![threshholds](https://user-images.githubusercontent.com/72523866/189354485-0e3410b7-a57a-4214-9280-27b4cb0209ce.png)

and the list looks like this
![image](https://user-images.githubusercontent.com/72523866/189354625-1f986b5f-459d-4d1a-9642-a4104c7a1c5a.png)

and i cant set the colors..

Is this  bug or am i doing something wrong?

Thanks!

**Comment by Slamkryp** [comment]
Right, running Grafana 9.1.3 and plugin 0.3.1

**Comment by knightss27** [comment]
Ah! I can't believe I haven't noticed that before. Your colors are there, just the color picker is white and on the left edge of each of those thresholds (and the default color is white...).

Try clicking on the left of the numbers, like here:

![image](https://user-images.githubusercontent.com/52898165/189412657-ae37cf78-bf92-4901-8988-bf47a084034e.jpeg)

In the meantime I ought to add a border to picker so you can see where it is.

**Comment by Slamkryp** [comment]
Ah! Of course! Why didnt i think of klicking there?

Well that did it! Thanks!

A simple border would fix it :-)

**Comment by knightss27** [comment]
Added for release with v0.3.2.
