### ISSUE TITLE
Throughput in percent

### ISSUE THREAD

**Issue by OCrylic** [knightss27/grafana-network-weathermap#24]
Hi,

Awesome work on this plugin. We are using it with Zabbix and it works nicely.

I have one request though.

Is it possible to add the possibility to display the throughput in percentage according the bandwidth ?
Also, to add the possibility to choose between the type of value to display on the link (throughput or throughput in percent or both)

We can see the range by looking at the color, but if we have a large scale (for example red for 80% to 100%), it would be interesting to check quickly by looking at the value in percent (81% is not the same as 99%).

Thanks

**Comment by knightss27** [comment]
Added for release with v0.3.2. You can now see the percentage throughput either on each link (if you turn it on), or at any time by hovering over the link. You can also toggle all links as percentages in the Link Options section of the editor (*note: this is does not override link-specific settings, so you can turn it on and back off and keep some links as percentages when it's off).

**Comment by OCrylic** [comment]
Hi @knightss27,
Great! Looking forward to try it as soon as it is released.
