### ISSUE TITLE
Zabbix datasource gives "wide" as only option for queries

### ISSUE THREAD

**Issue by juancamedrano21** [knightss27/grafana-network-weathermap#28]
Hello,

All the Query that were previously working have disappeared.

In its place in all it says: WIDE

[](url)
![error plugin](https://user-images.githubusercontent.com/64617144/195453164-0cdb5d53-49fb-4828-bb85-fcff7de4245f.png)

What can be causing this?

**Comment by knightss27** [comment]
Not sure why this would happen suddenly if you hadn't altered the queries. What do your queries look like?

**Comment by juancamedrano21** [comment]
@knightss27 is a Metrics from Zabbix Server with de Zabbix dataSoure

![image](https://user-images.githubusercontent.com/64617144/195469272-f2742471-1390-466d-96fe-cf90489a1adf.png)

**Comment by knightss27** [comment]
Ok, great! I just realized I've seen this issue before. Can you try disabling the "data alignment" option for the Zabbix datasource?

You can see here as well:
https://github.com/knightss27/grafana-network-weathermap/issues/7#issuecomment-1131874184

Please let me know if it works! I might add this to the FAQ if it does.

**Comment by juancamedrano21** [comment]
@knightss27 nice!!, It is already working correctly.

**Comment by lfmullen** [comment]
I'm still experiencing this issue on some dashboards, even after disabling data alignment on the dashboards and also on the datasource as a whole.

Has anyone else had similar issues?
