### ISSUE TITLE
Names with Prometheus should be Grafana's

### ISSUE THREAD

**Issue by eyalzo** [knightss27/grafana-network-weathermap#30]
**Describe the problem**
When fetching data from Prometheus, the names are taken directly from Prometheus, showing only the labels.
I'm using 0.3.2 (manual installation). With version 0.3.1 I couldn't use bandwidth queries at all (it displayed just "No Label").

**To Reproduce**
Steps to reproduce the behavior (if possible):
Use a Prometheus server. 

**Expected behavior**
It would better use Grafana's naming system, meaning the series name (A,B etc) or Grafana's labeling system for Prometheus (as performed by Duagram plugin for example).

**Screenshots**
The first query (out of two), that has a unique legend name and a unique series name:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/1243760/197479847-7cfc1b6e-fa0c-4135-b0a5-ff9e1b80ccd1.png">

How the two queries appear in the plugin's select box:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/1243760/197480023-107dd995-124c-4bb1-b205-d550fc7980e1.png">

**VERSIONS! (please complete the following information):**
 - Browser Chrome
 - Grafana Version 9.2.0
 - Plugin Version 0.3.2

**Comment by knightss27** [comment]
Fixed with v0.3.3. I've submitted it for Grafana's review, so should be live sometime this week (skipping v0.3.2 for Grafana's own site).

**Comment by eyalzo** [comment]
It's working! Version 0.3.3. Thanks a lot.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/1243760/197621645-e61d2a9d-447f-4a90-a4fc-c8e65254a41b.png">

**Comment by eyalzo** [comment]
It should be noted that there is still a minor bug there (?)- seems like it's impossible to delete the query, meaning to say something like "I regret and would like to leave this field empty". I think there should be an X for that.
See for example the X here in the Node's status (it doesn't reset that field either, btw):
<img width="578" alt="image" src="https://user-images.githubusercontent.com/1243760/197623123-b520ca84-da20-4844-a2e0-9513c6598364.png">

**Comment by knightss27** [comment]
Good catch, I need to add a clearing option for the other fields. I'll make sure this gets in the next update.
