### ISSUE TITLE
Not able to define different usage for each links

### ISSUE THREAD

**Issue by Umar3331** [knightss27/grafana-network-weathermap#35]
**Problem**
I am planning to create this weathermap, example i am taking four nodes and creating two links between them, example from node a to node b and from node c to node d.
![image](https://user-images.githubusercontent.com/63320369/204561617-674e01b7-a085-4f07-8768-902baf036445.png)

then i have elasticsearh index which contains information of outBps and InBps then i create a query which will pull outBps and InBps for each link, 
![image](https://user-images.githubusercontent.com/63320369/204561976-f908c3dd-9637-40ab-85b6-d0b36f6e51cc.png)
![image](https://user-images.githubusercontent.com/63320369/204562130-45a62729-37b3-48a0-813d-f00835240dd2.png)

so when i am trying to select this created query on the right side panel of A side and Z side it is not able to differentiate between these query and eventually gives me the same output 
![image](https://user-images.githubusercontent.com/63320369/204562819-d0e3d72f-a85b-4a8f-b192-76f55f58d57e.png)

**Expected behavior**
i should be able to select different usage from the queries of different links
![image](https://user-images.githubusercontent.com/63320369/204563941-e0024c40-4ca3-44b3-80c5-71360c111077.png)
like this how is this achievable 

**VERSIONS! (please complete the following information):**
 - Browser [firefox]
 - Grafana Version [8.5.11]
 - Plugin Version [0.3.3]
 - Additional (Elasticsearch is being used as a data source)

so please help screen shot is attached, Thank you

**Comment by Umar3331** [comment]
if you can help with some mock examples of this weathermap collecting data from ealsticsearch?

**Comment by knightss27** [comment]
Yes, if the queries have the exact same name they're going to be selected as the same. I can't really do much about this since there is no other better way to track queries unfortunately. Are you able to just add a some pattern in the "Alias" field of Elasticsearch to make the queries differently named?
