### ISSUE TITLE
Same problem: I am unable to select one of my data queries. 

### ISSUE THREAD

**Issue by vodotsenko** [knightss27/grafana-network-weathermap#38]
Your recommendation:
"See the note on: [Adding Data](https://grafana-weathermap.seth.cx/#adding-data)."

There is the following note:
"PLEASE NOTE: Queries with the exact same labels will be considered as such. If you have multiple queries and are unable to select the one that you want, double check to make sure it is labeled uniquely."

Please explain to me where can I check the uniqueness of an query. 
There are no uniqueness marks on the panel. I only see the following options: duplicate, hide, delete.

File:
![Screenshot_20221222_124208](https://user-images.githubusercontent.com/119850421/209066087-960b78bd-b6da-428f-9be6-26a59ea5a725.png)

**Comment by knightss27** [comment]
I'm not entirely sure the best place to check this, though I wonder if in the "options" dropdown for the query (below "Functions") are you able to add something to distinguish the two?

**Comment by vodotsenko** [comment]
After enabling these options, nothing happens. Where can I enable query uniqueness?

![Screenshot_20221226_164816](https://user-images.githubusercontent.com/119850421/209534659-789a57b0-86f5-456a-825e-e206ccd37cc5.png)

**Comment by knightss27** [comment]
Maybe this is a different version of #7? Can you try disabling "data alignment" in the options of the Zabbix data source?

**Comment by vodotsenko** [comment]
Disabling "data alignment" does nothing. (screenshot 1 and 2).
However, if I remove one of the queries from visibility, then I can select "Traffic Out" for "Z Side Query". Of course "Traffic In" doesn't work anymore (screenshot 3)

screenshot 1
![1Screenshot_20221226_164816](https://user-images.githubusercontent.com/119850421/209615024-6f0e0d6a-0fa3-4ae7-bd17-a4329893f2cd.png)

screenshot 2
![2Screenshot_20221227_121019](https://user-images.githubusercontent.com/119850421/209615030-c2ec887b-53c1-4bcd-bc62-305279f4c876.png)

screenshot 3
![3Screenshot_20221227_121111](https://user-images.githubusercontent.com/119850421/209615471-2e089a49-3a9a-4184-88c3-bdba7ed54a62.png)

**Comment by knightss27** [comment]
This is weird. Can you make sure both queries are enabled and then at the top (possible outside of edit mode) click on the name of your panel and select "Inspect" > "Panel JSON" and then change the dropdown at the top to "Panel Data" and attach the file to a response? Feel free to remove some of the pure data values and/or change names if you don't want to share that info.

**Comment by vodotsenko** [comment]
I'm attaching the requested file (Panel_data_Inspect_NSK-Core.txt).

You can see the current configuration in the screenshot.

![4Screenshot_20221227_131247](https://user-images.githubusercontent.com/119850421/209620252-3049eb1b-4013-468e-a6d0-ede60183cbc3.png)

[Panel_data_Inspect_NSK-Core.txt](https://github.com/knightss27/grafana-network-weathermap/files/10306273/Panel_data_Inspect_NSK-Core.txt)

**Comment by knightss27** [comment]
Can you go to the actual Zabbix settings, so "Configuration" > "Datasources" on the left hand side of Grafana, and try disabling data alignment there (not just on the individual queries)? It looks to me like this might still be causing a problem.

**Comment by vodotsenko** [comment]
I tried turning off data alignment in the global settings, but after creating a new Weathermap, nothing has changed. I have also played around with the query settings separately, but I can't select "Traffic Out" from the "x Side Query" dropdown.
![5Screenshot_20221227_132812](https://user-images.githubusercontent.com/119850421/209622763-316b4955-27c1-4522-a084-43345a75867f.png)
![6Screenshot_20221227_132928](https://user-images.githubusercontent.com/119850421/209622770-5bde37ba-24c1-412a-9163-e44a3e53cdaf.png)
![7Screenshot_20221227_133004](https://user-images.githubusercontent.com/119850421/209622772-a2e09b64-4203-4b0a-a4e6-22c5fbb959fe.png)

**Comment by knightss27** [comment]
Hmm. Ok a final two thoughts to try:

1. Can you write these queries a different way? i.e. https://alexanderzobnin.github.io/grafana-zabbix/guides/gettingstarted/#multiple-items-on-one-graph (so both options are originating from Query A)? I don't use Zabbix myself so I'm not sure if this works for your situation, but it looks like you are able to get multiple outputs from a singular Grafana query field.
2. What does the "item tag" field do? Is it able to change the names of the items?

**Comment by vodotsenko** [comment]
1. Looks like it works here. I will test other visualization methods later.
![8Screenshot_20221227_140356](https://user-images.githubusercontent.com/119850421/209626570-b653f491-4f6a-41d5-a81e-2fe192ddc3fd.png)

2. This is just a tag (for convenience). I can't change the names this way.
![9Screenshot_20221227_140537](https://user-images.githubusercontent.com/119850421/209626589-8f7f45df-125d-46b7-9a45-2eef88e03c16.png)

**Comment by cameronw1996** [comment]
I had this same issue. I had to add 3 or more queries of different devices and the drop down list then started to work. If I only add 2 queries I could only choose one from the drop down. I wondered if it might be bug?

**Comment by vodotsenko** [comment]
Now I have added 10 requests for different network devices, but nothing has changed. The dropdown list doesn't work properly, I mean I can only select one (first added) query. @cameronw1996, perhaps you have changed something else?

**Comment by knightss27** [comment]
In the "Item" field for the first query (Query A), are you able to do Regex like "/.*/" or equivalent? Instead of having two separate queries? This is what I was trying to say above but I wasn't sure how to put it. I can see from this [other issue](https://github.com/knightss27/grafana-network-weathermap/issues/40#issue-1530321108) with a Zabbix user that they can select multiple "items" by using regex in the "Item" field, so I wonder if this might fix your issue?

**Comment by vodotsenko** [comment]
Finally! The problem has been fixed. Can you specify this singularity in the documentation for Zabbix database users?

Thanks so much for your help. This project is great!

**Comment by knightss27** [comment]
Great! Yes, I am going to work on updating the documentation page as a whole and I will add this issue.

**Comment by bingsiL** [comment]
> Great! Yes, I am going to work on updating the documentation page as a whole and I will add this issue.

Sorry, I didn't understand how to solve the author's problem, can you give a detailed explanation?
