### ISSUE TITLE
Problem with empty data frame

### ISSUE THREAD

**Issue by OCrylic** [knightss27/grafana-network-weathermap#40]
**Describe the problem**
Hi @knightss27,

I use the Zabbix datasource and I have a problem when the query send an empty data frame.
I have a map with 50 queries and if only one of them is sending an empty data frame, it breaks the entire map and I have the error "a is undefined":
![image](https://user-images.githubusercontent.com/89840295/212015233-6a18b4f9-3df1-4b0a-95dc-66bd5fa1bf96.png)
Having a query sending null values is normal and could happen as sometimes I have no value or my host or my interface does not exist in Zabbix yet. But it should not break the entire map.

Usually, when I have no value, the query send nothing (null or empty?). But I am using a specific function (to sum my series) that transform it into a data frame with no result and I think this is what is causing the problem.
Here is the example displaying the data in a table without and with the function I use. The second one fails in a network weathermap panel
OK in network weathermap panel (display 0 on link):
![image](https://user-images.githubusercontent.com/89840295/212017995-a84febcf-059d-4ec5-a85e-7f9d9860cce5.png)

NOK in network weathermap panel (I have the error and cannot see the map in the panel)
![image](https://user-images.githubusercontent.com/89840295/212018533-ea045503-9c04-4569-800c-8cdfc1382b8c.png)

**To Reproduce**
You can reproduce it with the Zabbix datasource as I showed in the screenshot, by putting a host or an interface that does not exists and using the sumseries function

**Expected behavior**
I expect the Network Weathermap panel not failing and display 0 or n/a if it is an empty data frame

**Versions**
 - Grafana version 9.3.1
 - Network Weathermap Plugin version 3.3
 - Zabbix plugin version 4.2.10

**Comment by knightss27** [comment]
Can you confirm whether this breaks using this query for both the "bandwidth" and normal throughput "query" fields? Or does it just break if you're using that query for bandwidth or only for the throughput? Or does the panel break even if you haven't added the query to a specific link?

**Comment by knightss27** [comment]
I pushed a possible fix for this with the new update that has just been released on Grafana. Please let me know if this still happens, and I'll try and debug it further.

**Comment by OCrylic** [comment]
Hi @knightss27 

It did the trick, thank you

**Comment by ladvocat** [comment]
I am having the same problem described in this case.
But instead of Zabbix, I use Influxdb v2.
When a router is down and the query fails to retrieve data, the map crashes.
I have tried to update to version 0.3.5 but it did not resolve the problem. 
To replicate this behavior is as easy as to add a link connected to a "broken" query.
