### ISSUE TITLE
Unable to see new queries in dropdown

### ISSUE THREAD

**Issue by Derova** [knightss27/grafana-network-weathermap#43]
Thanks in advance for building this, I've used PHP Weathermap in the past and it's nice to have something in Grafana with an InfluxDB backend.

The bug I'm encountering is additional queries are not showing up in the Links A Side / Z Side Dropdown
Tested in both Chrome and Firefox (and in private browser tabs)

Example Screenshot:
Query A (ESX1-DATA-OUT) shows
Query B (ESX1-DATA-IN) shows
Query C (ESX2-DATA-OUT) doesn't show

![Screenshot from 2023-02-01 14-39-29](https://user-images.githubusercontent.com/48076842/215939514-186cc9de-32fe-4d4b-bbae-932bf521acaa.png)

**Comment by knightss27** [comment]
That's odd. Would you be able to go to the top of your panel, where you usually click to edit, and then press "Inspect" > "Panel JSON" and at the top choose "DataFrame JSON" and then send the JSON here? Feel free to edit the data if it has any sensitive names you don't want posted / concatenate any large rows of data.

**Comment by Derova** [comment]
Wow, thanks for the fast response!
Information attached as requested.

[DataFrame JSON.txt](https://github.com/knightss27/grafana-network-weathermap/files/10553176/DataFrame.JSON.txt)

**Comment by Derova** [comment]
Whoops, Sorry about that.
Clicked Close with Comment instead of Comment by mistake.

**Comment by knightss27** [comment]
Well it doesn't look to me like a problem with the weathermap itself as in your JSON there the frame only shows two queries (A and B), and no C query, which means the weathermap isn't receiving query C in any form. Still here are some things you could try:

1. Does hitting refresh at the top of the panel help (you might just need to get Grafana to run the query)? 
2. When you inspected the data, the third C query was saved, right?
3. Are you able to see all three queries if you recreate them in a simple line graph panel?

**Comment by Derova** [comment]
1. Refresh and Force Refresh doesn't make a difference.
2. Yes, the third query was saved. If I close Grafana and reload the page (in a new browser even) and edit the panel, the C query is there.
3. It doesn't show up in a Line Graph, I suspect this Grafana panel might be broken.

Thanks for your assistance! I'll delete this panel and try in a new one.

**Comment by Derova** [comment]
@knightss27 I really really appreciate the quick response and assistance in isolating this for me.
Embarrassed to admit it was bad data on my side for the device under Query C!

Love the work, and really excited to see a decent weathermap tool come to Grafana!

**Comment by knightss27** [comment]
Thanks so much, and no worries, I'm always happy to help! Feel free to let me know if you have any other issues.
