### ISSUE TITLE
Link with 0 bps presenting an old value

### ISSUE THREAD

**Issue by ladvocat** [knightss27/grafana-network-weathermap#47]
**Describe the problem**
When a link between two routers is down, it should present a black line (0 bps), but it is presenting a value like a query as "Last Not Null value".

**To Reproduce**
Create a link that has traffic and then shutdown the interface or empty the utilization to have 0 bps in it.

**Expected behavior**
When the link between two routers is down, it should present a black line (0 bps).

**Screenshots**
![Screenshot from 2023-03-06 16-02-27](https://user-images.githubusercontent.com/16313126/223209120-723b5549-e801-467e-a38d-f2e6f662d265.png)

![Screenshot from 2023-03-06 16-03-08](https://user-images.githubusercontent.com/16313126/223208749-40062c86-fbb5-4bbc-92f2-11bf39a1a640.png)

**VERSIONS! :**
 - Browser: chrome, firefox
 - Grafana Version 9.3.1
 - Plugin Version 0.3.5
 - Influxdb v2

**Comment by knightss27** [comment]
This should be fixed now, will be released soon with the next patch.
