### ISSUE TITLE
Last value 0 being showed as n/a

### ISSUE THREAD

**Issue by verlique** [knightss27/grafana-network-weathermap#51]
We have a homebuilt SNMP collector storing the information in a InfluBD and I use queries to get the column with traffic information.

I notice that when I have my last value received being 0, the connection shows as n/a, as the image below shows:
![image](https://user-images.githubusercontent.com/25332933/226952182-b1373f72-ef84-4413-962e-4a48b657ae6f.png)

If I check on the table view I have the expected value, being 0 (zero)
![image](https://user-images.githubusercontent.com/25332933/226952549-2a80edb6-124e-4b4f-969b-06507eb7f6aa.png)

 - Browser chrome
 - Grafana Version v9.4.3
 - Plugin Version 0.3.5
 - Additional Versions
 -  - InfluxDB

**Comment by knightss27** [comment]
This is my bad, there was unintentional logic considering 0 values as not available. I will release a new update soon with the fix.
