### ISSUE TITLE
Automatically create charts for links

### ISSUE THREAD

**Issue by damianostom** [knightss27/grafana-network-weathermap#54]
Hello, while creating the map, I noticed that after hovering the cursor over the link, the link bandwidth graph is displayed. Is there a way to automate it so that I can automatically create a link to the Time Series chart? Currently, with 100 currently monitored ports, it is quite tedious to create as many as 100 charts manually and then configure the links manually.

Somehow these graphs are already created automatically, maybe you just need to share them.

Thank you!

**Comment by knightss27** [comment]
Though this does seem useful, I don't think I'm able to do this as my plugin is limited to accessing the data passed to it and its own settings, so it would be impossible for me to create other chart panels (and I would need to put them on a specific dashboard anyways). These graphs are currently made by rendering Grafana's timeseries graph component inside of the weathermap's panel, but this is just a React component that I'm passing the data to, not a separate timeseries panel.

**Comment by bardahlm** [comment]
Sorry for commenting on a closed issue!

It would be enough to construct a link where node and link is populated with relevant values.

https://grafana.example.com/<generic link graph dashboard>?var-host=${A side node}&var-interface=${link node A interface name}.

Getting the correct host and interface values requires the query to return usable labels.
