### ISSUE TITLE
Ability to turn off zoom

### ISSUE THREAD

**Issue by davesbell** [knightss27/grafana-network-weathermap#8]
This plugin is something I've been looking for, for a long time, and is amazing. Thank you!

I would very much like it if you had a toggle that would turn off the zoom functionality. I don't find it particularly useful, and it's quite annoying when it captures my mouse wheel when scrolling through some weathermaps.

**Comment by knightss27** [comment]
Frankly unsure why I default to zoom ability as it stands, so I'm more than happy to add a toggle for this. Will add this in the next release.

**Comment by davesbell** [comment]
Perfect! Thank you!
