### ISSUE TITLE
How to draw multiple parallel links between nodes?

### ISSUE THREAD

**Issue by lonelyadmin** [knightss27/grafana-network-weathermap#85]
I'm having a difficult time getting multiple parallel links defined between two nodes. I'm trying to do something similar to what is show in the examples between nodes A and B. I'm using prometheus as a datasource and already worked past the queries needing a label issue. I can get two links to work by moving the anchors to top, bottom, or whatever. But that won't work when I try with four or more links.

Without changing the anchors, the links just stack on one another between nodes when added.

Help!

**Comment by KrystianPlichta** [comment]
Any way to do this?
![image](https://github.com/user-attachments/assets/2d2aa254-2156-42f0-83ef-a9eebe8ea9fd)

**Comment by henriklb** [comment]
How did you solve this? I have the same issue with using anchors. I can manage max 3 parallel links (right, center, left, anchor points on each node)

**Comment by henriklb** [comment]
I found the solution from the wiki
>By default, links are auto-spaced to be as far apart as possible when parallel to each other vertically (attached to a Bottom of one link, and Top of another). When parallel horiztonally (attached to a Right of one link, and Left of another), nodes will automatically grow to accomodate them.

https://grafana-weathermap.seth.cx/customization/#link-options
